server:
  port: 12018
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yyhztzg2/test12.git
  rabbitmq:
    host: 172.21.4.157
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh